apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    CREATE TABLE etudiants (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, nom VARCHAR(20));
    INSERT INTO `etudiants` (`id`,`nom`) VALUES (NULL, "Stephane Brillant");
    INSERT INTO `etudiants` (`id`,`nom`) VALUES (NULL, "John Doe");
    INSERT INTO `etudiants` (`id`,`nom`) VALUES (NULL, "Leeroy Jenkins");
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: pass
        - name : MYSQL_DATABASE
          value: uqar
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-initdb
        configMap:
          name: mysql-initdb-config