apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts-cm
data:
  locustfile.py: |
    from locust import HttpUser, task
    class WebUser(HttpUser):
        @task
        def etudiants(self):
            self.client.get("/etudiants")